language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

env:
  global:
    # BINSTAR_TOKEN
    secure: "pLBnqE/XJEEx1cxtrkWFMs8Hb+l+jL/PmqZy8SGQCyNg931fpqzxIlno8E/xwydMzhczEFmT8uoozK/XRjVk4WSwzTZDPmIFtZCmMKUxgEpQav8tJjEZUfCKF254Vqws6OzUMnCSqZdV4oo8gD9ukmY1G64fPhMIHpDIoENYv/Q="
  matrix:
    - python=2.7  CONDA_PY=27
    # - python=3.3  CONDA_PY=33
    # - python=3.4  CONDA_PY=34

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - source devtools/travis-ci/test.sh

after_success:
  - source devtools/travis-ci/after_success.sh
