language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  global:
    # secure: ""
  matrix:
    - python=2.7  CONDA_PY=27
    # - python=3.3  CONDA_PY=33  PYTHONPATH=/home/travis/bin/modeller9.14/modlib:/home/travis/bin/modeller9.14/lib/x86_64-intel8/python3.3  LD_LIBRARY_PATH=/home/travis/bin/modeller9.14/lib/x86_64-intel8
    # - python=3.4  CONDA_PY=34  PYTHONPATH=/home/travis/bin/modeller9.14/modlib:/home/travis/bin/modeller9.14/lib/x86_64-intel8/python3.3  LD_LIBRARY_PATH=/home/travis/bin/modeller9.14/lib/x86_64-intel8

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
